modLoader = "javafml" #mandatory
loaderVersion = "[43,)"
license = "MIT"
[[mods]] #mandatory
modId = "curiotiab" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Curiotiab" #mandatory
description = '''
    Adds a Curio slot for Time in a bottle
'''
[[dependencies.curiotiab]]
modId="forge"
mandatory=true
versionRange="[40.1.60,)"
ordering="NONE"
side="BOTH"

[[dependencies.curiotiab]]
modId="curios"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"

[[dependencies.curiotiab]]
modId="tiab"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"
